Add package version check to frontend release

diff --git a/.github/workflows/frontend-release.yml b/.github/workflows/frontend-release.yml
--- a/.github/workflows/frontend-release.yml
+++ b/.github/workflows/frontend-release.yml
@@ -21,6 +21,17 @@ jobs:
           flavor: latest=false
           images: concordium/ccdscan-frontend
           tags: type=match,pattern=frontend/(.*),group=1
+      - name: Ensure tag matches version in package.json
+        run: |
+          EXPECTED=$(jq -r .version frontend/package.json)
+          EXTRACTED="${{ steps.meta.outputs.version }}"
+          if [ "$EXPECTED" = "$EXTRACTED" ]; then
+            printf "Extracted version matches the version in package.json ($EXTRACTED).\n"
+            exit 0
+          else
+            printf "ERROR: Extracted version does not match the version in package.json. \nExtracted: '$EXTRACTED'\nExpected: '$EXPECTED'\n"
+            exit 1
+          fi
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
